### PR TITLE
IB audio task

### PR DESCRIPTION
**Pull request by IrfanBoen**
This is the sprint task for the audio classification task. This task has been done in a group project of 3 people including me. The people that worked on this task are:
- IRFAN BOENARDI
- RILEY BECKETT
- VENESH KANAGASINGAM

### CODE REVIEW

**Review by minhD03 — CHANGES_REQUESTED** [review]
Please separate the coding part and data. You only need to upload the code and documents in here. For data, you can put it in another platforms like One Drive and share the link here. Thank you.

**Comment by IrfanBoen** [comment]
I had commited and push the updated audio task with only having the code and document inside of it. For the data itself i had kept it on a onedrive link, i made sure that only deakin people can access the link, so make sure to use your deakin accounts when accessing the link to see the data. If you have any problem please message me:
https://deakin365-my.sharepoint.com/:f:/r/personal/s224305795_deakin_edu_au/Documents/[Data](https://deakin365-my.sharepoint.com/:f:/r/personal/s224305795_deakin_edu_au/Documents/Data?csf=1&web=1&e=OEAdDq)?csf=1&web=1&e=OEAdDq

**Comment by IrfanBoen** [comment]
and regarding the GCP. I will try and upload the data to GCP and everything if i do have the time. But please do understand that there is a chance that i might not be able to do it because currently i am doing sprint 2 task and also the time is limited. Hopefully thats ok with you. Thanks

**Comment by regina-arissa** [comment]
I will close this pull request as it is not in the correct folder

**Pull request closed without merging**
