### PR TITLE
EE/AG/echo-local-library - Library toPlot MelSpectogram

### PR DESCRIPTION
**Pull request by abhitgahlot**
Library to plot Melspectogram and wavefrom from audiofile path

### CODE REVIEW

**Comment by mic-0-hal** [comment]
Looks like a good start with this one. For the spectogram function 
Dane has a workbook pending review for plotting the spectrogram. He is building it to be a big powerful function call. Can you reach out and work to integrate it into the library

A working notebook is all we are after.

**Comment by abhitgahlot** [comment]
@mic-0-hal , I have now successfully added the functions you mentioned to the library.

**Comment by cpavia** [comment]
A few spelling errors in the README. Can you please review?

**Comment by abhitgahlot** [comment]
@cpavia, The spelling mistakes in the read me file and the have been updated.

**Review by cpavia — APPROVED** [review]

**Pull request merged**
