### PR TITLE
EE/DP/Additonal_Endangered_Species

### PR DESCRIPTION
**Pull request by DonalPereira**
1. The data/audio was scraped from Youtube using scraping code.
2. Event segmentation was performed on each file for identifying events in the audio and saved as multiple outputs.
3. Manual cleaning was performed and stored as zip folder and shared through google drive.

### CODE REVIEW

**Comment by mic-0-hal** [comment]
Hi, can you add the python script for this please

**Review by mic-0-hal — CHANGES_REQUESTED** [review]
Can you add the python script for this please

**Comment by DonalPereira** [comment]
Python scripts for these already exist in Github as per below:
1. For scraping audio from Youtube: 
https://github.com/DataBytes-Organisation/Project-Echo/blob/main/src/Prototypes/data/scraping/Youtube%20video%20to%20audio%20(.wav%20format)/Youtubescraping.ipynb
2. For event segmentation:
https://github.com/DataBytes-Organisation/Project-Echo/blob/main/src/Prototypes/engine/Event_Segmentation_YamNet/Event_Segmenter.ipynb

**Comment by DonalPereira** [comment]
The README.md file for scraping tool used is as below:
https://github.com/DataBytes-Organisation/Project-Echo/blob/main/src/Prototypes/data/scraping/Youtube%20video%20to%20audio%20(.wav%20format)/README.md

**Review by mic-0-hal — APPROVED** [review]
Looks great to me. Well done

**Pull request merged**
