### PR TITLE
Ee/AKk/australian birds sourced from xeno canto

### PR DESCRIPTION
**Pull request by AtharvaKulkarni26**
A Pandas Dataframe and a readme file with a summary of Australian birds sourced from xeno-canto.org

### CODE REVIEW

**Comment by cpavia** [comment]
Hi ATHARVA, 

Thanks for the detailed README file. I'm working out the best location for this information and the csv file itself so future students can access it. I'll provide an update soon.

Cheers, Charmaine

**Comment by cpavia** [comment]
Hi Atharva,

Can you please move the contents of the Data summary folder to the following location. You can then delete the Data summary folder as it will be empty. 

GitHub\Project-Echo\src\Prototypes\data\scraping

**Comment by AtharvaKulkarni26** [comment]
Hey Charmaine, 

I just moved all the content there. 👍

**Comment by cpavia** [comment]
Perfect! Thank you

**Review by cpavia — APPROVED** [review]

**Pull request merged**
