### PR TITLE
EE\DLe\Weather-Detection-Model

### PR DESCRIPTION
**Pull request by dlees27**
Added a weather detection model. Saved as a .h5 file, and a .keras file

Model trained to a 93% accuracy, correctly identifying 28/30 for images from the single prediction dataset

### CODE REVIEW

**Review by Ank9812 — CHANGES_REQUESTED** [review]
Hey mate! 
just also attach the Jupyter file that you used to train this model! Thanks all.

**Comment by cpavia** [comment]
Hi Dane, this is looking good. 

Can you please add a README so others can easily use this file. Happy if you add a description to the top of the Jupyter file.

Here is an example: GitHub\Project-Echo\src\Prototypes\engine\yamnet\READ_ME.ipynb

Maybe create a new folder for all the weather detection artefacts?

**Comment by dlees27** [comment]
Hi Charmaine,

I will do this ASAP after work today

**Comment by dlees27** [comment]
Done

**Review by cpavia — APPROVED** [review]

**Comment by cpavia** [comment]
Great work Dane!

**Review by Ank9812 — APPROVED** [review]

**Pull request merged**
