### PR TITLE
Ee/cp/species metadata wip

### PR DESCRIPTION
**Pull request by cpavia**
Merged changes from team

### CODE REVIEW

**Review by mic-0-hal — COMMENTED** [review]
`ValueError                                Traceback (most recent call last)
[/Users/mhallid2/Downloads/Species_MetaData.ipynb](https://file+.vscode-resource.vscode-cdn.net/Users/mhallid2/Downloads/Species_MetaData.ipynb) Cell 5 line 9
     [90](vscode-notebook-cell:/Users/mhallid2/Downloads/Species_MetaData.ipynb#W4sZmlsZQ%3D%3D?line=89) path = "[/Volumes/UGREEN](https://file+.vscode-resource.vscode-cdn.net/Volumes/UGREEN) Samsung SSD/project echo audio/Production data/PRODUCTION TRAINING/Training data"
     [92](vscode-notebook-cell:/Users/mhallid2/Downloads/Species_MetaData.ipynb#W4sZmlsZQ%3D%3D?line=91) # Create metadata df
---> [93](vscode-notebook-cell:/Users/mhallid2/Downloads/Species_MetaData.ipynb#W4sZmlsZQ%3D%3D?line=92) df = CreateMetaData(path)

[/Users/mhallid2/Downloads/Species_MetaData.ipynb](https://file+.vscode-resource.vscode-cdn.net/Users/mhallid2/Downloads/Species_MetaData.ipynb) Cell 5 line 7
     [72](vscode-notebook-cell:/Users/mhallid2/Downloads/Species_MetaData.ipynb#W4sZmlsZQ%3D%3D?line=71) seconds = GetAudioDurations(path, classes, filenames)
     [73](vscode-notebook-cell:/Users/mhallid2/Downloads/Species_MetaData.ipynb#W4sZmlsZQ%3D%3D?line=72) feature_colname = ['filename', 'seconds', 'class']
---> [74](vscode-notebook-cell:/Users/mhallid2/Downloads/Species_MetaData.ipynb#W4sZmlsZQ%3D%3D?line=73) df = pd.DataFrame({'Class': classes, 'Filename': filenames, 'Filesize': filesizes, 'Seconds': seconds, 'Filesize_by_class': classsizes})
     [75](vscode-notebook-cell:/Users/mhallid2/Downloads/Species_MetaData.ipynb#W4sZmlsZQ%3D%3D?line=74) df['Seconds'] = df['Seconds'].fillna(0)
     [76](vscode-notebook-cell:/Users/mhallid2/Downloads/Species_MetaData.ipynb#W4sZmlsZQ%3D%3D?line=75) df1 = df.groupby('Class').agg({'Filename': 'count', 'Seconds': 'sum'}).reset_index()

File [~/anaconda3/envs/condabackupwedsep13/lib/python3.10/site-packages/pandas/core/frame.py:736](https://file+.vscode-resource.vscode-cdn.net/Users/mhallid2/Downloads/~/anaconda3/envs/condabackupwedsep13/lib/python3.10/site-packages/pandas/core/frame.py:736), in DataFrame.__init__(self, data, index, columns, dtype, copy)
    730     mgr = self._init_mgr(
    731         data, axes={"index": index, "columns": columns}, dtype=dtype, copy=copy
    732     )
    734 elif isinstance(data, dict):
    735     # GH#38939 de facto copy defaults to False only in non-dict cases
--> 736     mgr = dict_to_mgr(data, index, columns, dtype=dtype, copy=copy, typ=manager)
    737 elif isinstance(data, ma.MaskedArray):
    738     from numpy.ma import mrecords

File [~/anaconda3/envs/condabackupwedsep13/lib/python3.10/site-packages/pandas/core/internals/construction.py:503](https://file+.vscode-resource.vscode-cdn.net/Users/mhallid2/Downloads/~/anaconda3/envs/condabackupwedsep13/lib/python3.10/site-packages/pandas/core/internals/construction.py:503), in dict_to_mgr(data, index, columns, dtype, typ, copy)
...
    680     raise ValueError(
    681         "Mixing dicts with non-Series may lead to ambiguous ordering."
    682     )

ValueError: All arrays must be of the same length`

**Comment by mic-0-hal** [comment]
I gave this the bucket of folders of species and got this error

**Comment by cpavia** [comment]
Same here. 

We need to do some more testing it seems!

**Review by mic-0-hal — COMMENTED** [review]
downloading now

**Review by Q-Cooke — APPROVED** [review]
LGTM, thanks heaps

**Pull request merged**
