### PR TITLE
Tz api fixes

### PR DESCRIPTION
**Pull request by tzhai92**

### CODE REVIEW

**Comment by stephankokkas** [comment]
Want me to approve or you need someone else to review first?

**Review by stephankokkas — APPROVED** [review]
Looks fine to me. If you want someone else to review feel free to request it, otherwise you can merge as I have approved changes for you.

**Comment by tzhai92** [comment]
Yes but there's a conflict

**Comment by stephankokkas** [comment]
Looks like you've got some work to fix it then 😂

**Pull request merged**
