### PR TITLE
EE/TP/Transfer Learning using InceptionResNetV2

### PR DESCRIPTION
**Pull request by ptanmay143**
Hi Good Morning. I worked on using the InceptionResNetV2 model ([Engine- Transfer-learning with Inception on Major Product 1 - Project Echo | Trello](https://trello.com/c/yWznkcR0/314-engine-transfer-learning-with-inception)) on our optimised_engine_pipeline.

I got some errors running the code before even adding the InceptionResNetV2 model to the pipeline. Those were fixed by explicitly pinning some versions of the used python packages.

Later, I added the model to the pipeline and found that the InceptionResNetV2 model expects an input shape of (299, 299) instead of the (260, 260) that was already used in the pipeline. I modified the input shape in our pipeline and now the model has started to train without any compilation errors.

Currently at epoch 1/5000 at step 139/1577 it shows an ETA of 2:48:33.

EDIT: Current training running at https://drive.google.com/file/d/1BIJRGk002nPF8I2OAGGJ-yVkbjry_Abf/view?usp=sharing on Google Colab.

### CODE REVIEW

**Comment by ptanmay143** [comment]
image

**Comment by ptanmay143** [comment]
I believe that this low initial accuracy will improve over the epochs and as training progresses. Although, using a pre-trained InceptionResNetV2 model on ImageNet or another dataset with images, the initial weights may not be suitable for our spectrogram classification task.

**Review by mic-0-hal — COMMENTED** [review]
Quick tip. clear the cell outputs of the imports and it will keep the file cleaner and file-size down

**Review by mic-0-hal — COMMENTED** [review]
Change audio clip duration to 2 seconds as we are now using smaller file sizes
    'AUDIO_CLIP_DURATION': 2, # seconds

I had to comment out "tensorboard_callback" function as I was getting error:
[AttributeError: ‘function’ object has no attribute ‘history’]

**Comment by mic-0-hal** [comment]
Did you figure out the tensorboard error?

**Comment by ptanmay143** [comment]
> Did you figure out the tensorboard error?

I wasn't able to reproduce the error because the code ran fine on my side. Possibly because it only ran for just under an epoch, the tensorboard_callback was not called yet.

**Review by mic-0-hal — CHANGES_REQUESTED** [review]
Besides the errror on my end, it functions perfectly. I have trained the model on it

Please remove the .gitignore

**Review by mic-0-hal — APPROVED** [review]
Great work. LGTM

**Pull request merged**
