### PR TITLE
Ee/AKk/adding cam to spectograms

### PR DESCRIPTION
**Pull request by AtharvaKulkarni26**
This script contains a notebook that demonstrates the process of adding Class Activation Mapping (CAM) to spectrograms. The purpose of CAM is to provide visual explanations of which regions in the image were pivotal in making a prediction, making it an essential tool for model interpretability.

This PR has the script and readme.md file explaining the script.

### CODE REVIEW

**Comment by cpavia** [comment]
Hi Atharva, 

This is great work! Can you add a little extra to the description please. Something along the lines of 'This program creates Class Activation Mapping (CAM) and can be added to Spectograms.' 

Essentially, we want the user to know what they can or should do with this program if they come across it in the folders :)

**Comment by cpavia** [comment]
Also, can you please explain why I need an image folder and what you mean by 'at least three image files'?

You might need a better description to help a user use the program correctly. Can you please review? Thanks!

**Comment by AtharvaKulkarni26** [comment]
Hey Charmaine, 

I have made the requested changes and added an explanation in the commit please review it at your earliest convenience, if you need anything else please let me know, thank you!

**Comment by cpavia** [comment]
Hi Atharva, it's very close!

1. Do you need to run plot mel spec only.ipynb first? If so, can you add a brief description so it is clear what this script is for and when it should be used
2. In the above script, fix the formatting on line 7 and ensure you remove your personal directory in line 8 (replace with something generic).
3. If plot mel spec only.ipynb is run first, then you need to explain that the location of the images created in this script needs to be the location added at line 4 in class_activation_mapping.ipynb

Thanks!

**Comment by AtharvaKulkarni26** [comment]
Hey Charmaine, 

I have made the suggested changes!

**Review by mic-0-hal — APPROVED** [review]
Looks like you have addressed the changes. Look forward to seeing this applied to the EchoNet when that occurs

**Pull request merged**
